{% set name = "ozzy-pic" %}
{% set version = "1.0.6" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ozzy_pic-{{ version }}.tar.gz
  sha256: ea2629c92845abda5c3a5a51a54fcaa734a3b2b4438b9bc812c9ffddd2ce5ab1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }}
    - xarray >=2024.9.0,<2025.0.0
    - tqdm >=4.66.5,<5.0.0
    - numba >=0.60.0,<0.61.0
    - h5py >=3.12.1,<4.0.0
    - h5netcdf >=1.4.0,<2.0.0
    - flox >=0.9.12,<0.10.0
    - dask-core >=2024.10.0,<2025.0.0
    - dask-expr >=1.1.16,<2.0.0
    - matplotlib-base >=3.9.2,<4.0.0
    - cmcrameri
    - seaborn >=0.13.2,<0.14.0
    - ipython >=8.28.0,<9.0.0
    - ipykernel >=6.29.5,<7.0.0
    - hvplot >=0.11.1,<0.12.0
    - jupyter_bokeh >=4.0.5,<5.0.0
  run_constrained:
    - numpy-groupies >=0.11.2,<0.12.0
    - numbagg >=0.8.2,<0.9.0

test:
  imports:
    - ozzy
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://mtrocadomoreira.github.io/ozzy/
  summary: PIC simulation data analysis for the lazy and impatient
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mtrocadomoreira
