{% set name = "ozzy-pic" %}
{% set version = "1.2.9" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ozzy_pic-{{ version }}.tar.gz
  sha256: 53d65427c91f06b80ed91cec38f7bbb0b212f8d16c9627047f066a812b2823a0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }}
    - xarray >=2025.6.1,<2026.0.0
    - tqdm >=4.67.1,<5.0.0
    - numba >=0.61.2,<0.62.0
    - h5py >=3.14.0,<4.0.0
    - h5netcdf >=1.6.1,<2.0.0
    - flox >=0.10.4,<0.11.0
    - dask-core >=2025.5.1,<2026.0.0
    - dask-expr >=2.0.0,<3.0.0
    - matplotlib-base >=3.10.3,<4.0.0
    - cmcrameri
    - seaborn >=0.13.2,<0.14.0
    - ipython >=8.28.0,<9.0.0
    - ipykernel >=6.29.5,<7.0.0
    - hvplot >=0.11.1,<0.12.0
    - jupyter_bokeh >=4.0.5,<5.0.0
    - numbagg >=0.9.0,<0.10.0
    - pyarrow >=20.0.0,<21.0.0
  run_constrained:
    - numpy-groupies >=0.11.3,<0.12.0

test:
  imports:
    - ozzy
    - ozzy.plot
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://mtrocadomoreira.github.io/ozzy/
  summary: PIC simulation data analysis for the lazy and impatient
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mtrocadomoreira
